baseURL = "https://blog.lotp.xyz/"
title = "Lotp's Blog"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

theme = "hugo-paper"

[params]
  author = "lotp"
  name = "Lotp"
  bio = "Every Day in Life Is a First Time"
  avatar = "portrait.jpeg"
  github = "lo-tp"
  twitter = "lo__tp"
  linkedin = "shiqi-yang-6bbb73127"

[pagination]
  pagerSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
