#!/bin/sh
set -e
mkdir -p .bin

if [ ! -f .bin/hugo ]; then
  echo "Downloading Hugo..."
  curl --http1.1 -fsSL https://github.com/gohugoio/hugo/releases/download/v0.166.0/hugo_0.166.0_darwin_arm64.tar.gz | tar xz -C .bin
fi

exec .bin/hugo "$@"
